/*

 BREAKABLE_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char tiles[] =
{
  0xFF,0xFF,0xFD,0x83,0xFD,0x83,0xFD,0x83,
  0xFD,0x83,0xFD,0x83,0x81,0xFF,0xFF,0xFF,
  0xFF,0xFF,0x80,0xFF,0x87,0xF8,0xBF,0xC0,
  0x9F,0xE0,0x9F,0xE0,0x9F,0xE0,0x9F,0xE0
};

/* End of BREAKABLE_TILES.C */
