/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 19

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sprites_h_INCLUDE
#define __sprites_h_INCLUDE

/* Bank of tiles. */
#define spritesBank 0

/* Super Gameboy palette 0 */
#define spritesSGBPal0c0 6076
#define spritesSGBPal0c1 8935
#define spritesSGBPal0c2 6596
#define spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spritesSGBPal1c0 6076
#define spritesSGBPal1c1 8935
#define spritesSGBPal1c2 6596
#define spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spritesSGBPal2c0 6076
#define spritesSGBPal2c1 8935
#define spritesSGBPal2c2 6596
#define spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spritesSGBPal3c0 6076
#define spritesSGBPal3c1 8935
#define spritesSGBPal3c2 6596
#define spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spritesCGBPal0c0 22975
#define spritesCGBPal0c1 32767
#define spritesCGBPal0c2 26144
#define spritesCGBPal0c3 15360

/* Gameboy Color palette 1 */
#define spritesCGBPal1c0 6076
#define spritesCGBPal1c1 8935
#define spritesCGBPal1c2 6596
#define spritesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define spritesCGBPal2c0 6076
#define spritesCGBPal2c1 8935
#define spritesCGBPal2c2 6596
#define spritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spritesCGBPal3c0 6076
#define spritesCGBPal3c1 8935
#define spritesCGBPal3c2 6596
#define spritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spritesCGBPal4c0 6076
#define spritesCGBPal4c1 8935
#define spritesCGBPal4c2 6596
#define spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spritesCGBPal5c0 6076
#define spritesCGBPal5c1 8935
#define spritesCGBPal5c2 6596
#define spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spritesCGBPal6c0 6076
#define spritesCGBPal6c1 8935
#define spritesCGBPal6c2 6596
#define spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spritesCGBPal7c0 6076
#define spritesCGBPal7c1 8935
#define spritesCGBPal7c2 6596
#define spritesCGBPal7c3 5344

/* CGB palette entries. */
#define spritesCGB0 0
#define spritesCGB1 0
#define spritesCGB2 0
#define spritesCGB3 0
#define spritesCGB4 0
#define spritesCGB5 0
#define spritesCGB6 0
#define spritesCGB7 0
#define spritesCGB8 0
#define spritesCGB9 0
#define spritesCGB10 0
#define spritesCGB11 0
#define spritesCGB12 0
#define spritesCGB13 0
#define spritesCGB14 0
#define spritesCGB15 0
#define spritesCGB16 0
#define spritesCGB17 0
#define spritesCGB18 0
#define spritesCGB19 0
/* Start of tile array. */
extern const unsigned char sprites[];

#endif

/* End of SPRITES.H */
