/*

 TILES.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tiles_h_INCLUDE
#define __tiles_h_INCLUDE

/* Bank of tiles. */
#define tilesBank 0

/* Super Gameboy palette 0 */
#define tilesSGBPal0c0 6076
#define tilesSGBPal0c1 8935
#define tilesSGBPal0c2 6596
#define tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tilesSGBPal1c0 6076
#define tilesSGBPal1c1 8935
#define tilesSGBPal1c2 6596
#define tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tilesSGBPal2c0 6076
#define tilesSGBPal2c1 8935
#define tilesSGBPal2c2 6596
#define tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tilesSGBPal3c0 6076
#define tilesSGBPal3c1 8935
#define tilesSGBPal3c2 6596
#define tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tilesCGBPal0c0 31572
#define tilesCGBPal0c1 0
#define tilesCGBPal0c2 0
#define tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tilesCGBPal1c0 369
#define tilesCGBPal1c1 538
#define tilesCGBPal1c2 470
#define tilesCGBPal1c3 31572

/* Gameboy Color palette 2 */
#define tilesCGBPal2c0 369
#define tilesCGBPal2c1 538
#define tilesCGBPal2c2 470
#define tilesCGBPal2c3 711

/* Gameboy Color palette 3 */
#define tilesCGBPal3c0 32767
#define tilesCGBPal3c1 26425
#define tilesCGBPal3c2 10570
#define tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tilesCGBPal4c0 6076
#define tilesCGBPal4c1 8935
#define tilesCGBPal4c2 6596
#define tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tilesCGBPal5c0 6076
#define tilesCGBPal5c1 8935
#define tilesCGBPal5c2 6596
#define tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tilesCGBPal6c0 6076
#define tilesCGBPal6c1 8935
#define tilesCGBPal6c2 6596
#define tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tilesCGBPal7c0 6076
#define tilesCGBPal7c1 8935
#define tilesCGBPal7c2 6596
#define tilesCGBPal7c3 5344
extern const unsigned char tilesTLE0[];
extern const unsigned char tilesTLE1[];
extern const unsigned char tilesTLE2[];
extern const unsigned char tilesTLE3[];
extern const unsigned char tilesTLE4[];
extern const unsigned char tilesTLE5[];
extern const unsigned char tilesTLE6[];
extern const unsigned char tilesTLE7[];
extern const unsigned char tilesTLE8[];
extern const unsigned char tilesTLE9[];

#endif

/* End of TILES.H */
